spring:
  application:
    name: chatflow

  datasource:
    url: jdbc:postgresql://localhost:5432/chatflow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

# JWT config
jwt:
  secret: mohitkumar-chatflow-secret-key-change-this-in-prod
  expiration: 86400000

# App metadata
app:
  name: ChatFlow
  version: 0.1.0
  author: Mohit Kumar
